- name: master
  box: bento/ubuntu-18.04
  provider: vmware_fusion
  mem: 4096
  cpu: 4
  linkedclone: false
  nestedvt: true
  network:
    - kind: private_network
      ip: 10.0.0.2
      mask: 255.255.255.0


# This creates two nodes: node-100 10.0.0.3 , node-101 10.0.0.4
- name: "node-" #
  box: bento/ubuntu-20.04
  mem: 2048
  cpu: 2
  linkedclone: true
  nestedvt: false
  namelabel: true
  x11: true
  gui: false
  vram: 256
  replicas: 2
  replicaid: 100
  video3d: false
  network:
    - kind: private_network # NIC:eth1, Management Network (Host Only)  NIC: eth1
      ip: 10.0.0.3
      mask: 255.255.255.0
    - kind: public_network # NIC:eth2, Provider Network
      bridge: en8 # Ethernet Card
      auto_config: false
  disk:
    - size: 50 # Block Storage (size in GB)
  script:
    - cmd: "echo 'blah $$' >> /home/vagrant/blah.txt"
      privileged: false
    - cmd: "echo 'sudo blah $$' >> /home/vagrant/blah.txt"
      privileged: true
    - path: configure_replica.sh
      args: "$$" 
      privileged: true
    - path: finish_setup.sh
      args: [instance_$$.log,"--verbose"] # Replaced by replicaid
  share:
    - source: "./node-$$"
      disabled: false
      target: "/vagrant"
      create: true
      owner: "vagrant"
      group: "vagrant"
      options: ["uid=1234", "gid=1234"]
      sync: true
    - source: "dataset.csv"
      target: "/home/vagrant/dataset.csv"
      sync: false
    - source: "./project/src"
      target: "/home/vagrant/code"
      sync: false
