- name: master
  box: bento/ubuntu-18.04
  mem: 2048
  cpu: 2
  linkedclone: false
  nestedvt: true
  network:
    - kind: private_network
      ip: 10.0.0.2
      mask: 255.255.255.0
    - kind: public_network # NIC:eth2, Provider Network
      bridge: en0 # Ethernet Card
      auto_config: false
    - path: write_to_file.sh
      args: [/home/vagrant/i_am_again_$$.txt,"$$"] # Replaced by replicaid, defaults to 0
      privileged: false

# This creates two nodes: node-100 10.0.0.3 , node-101 10.0.0.4
- name: "node-" #
  box: bento/ubuntu-20.04
  mem: 1024
  cpu: 2
  linkedclone: true
  nestedvt: false
  namelabel: true
  x11: true
  gui: false
  vram: 256
  replicas: 2
  replicaid: 100
  video3d: false
  network:
    - kind: private_network # NIC:eth1, Management Network (Host Only)  NIC: eth1
      ip: 10.0.0.3
      mask: 255.255.255.0
    - kind: public_network # NIC:eth2, Provider Network
      bridge: en0 # Ethernet Card
      auto_config: false
  disk:
    - size: 50 # Extra disk 1 (size in GB)
    - size: 25 # Extra disk 2 , 25GB
  script:
    - cmd: "echo 'My replicaid is $$' > /home/vagrant/hello_$$.txt"
      privileged: false
    - path: write_to_file.sh
      args: "$$ /home/vagrant/i_am_$$.txt" 
      privileged: true
  share:
    - source: "./node-$$"
      disabled: false
      target: "/mnt/share"
      create: true
      owner: "vagrant"
      group: "vagrant"
      sync: true
    - source: "dataset.csv"
      target: "/home/vagrant/dataset.csv"
      options: ["uid=501", "gid=1000"]
      sync: false
    - source: "./project/src"
      target: "/home/vagrant/code"
      sync: false
